services:
  - type: web
    name: aml-admin
    env: java
    rootDir: aml-admin
    buildCommand: ./mvnw clean package || mvn clean package
    startCommand: java -jar target/*.jar
    plan: starter
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase: amlengine-db
        property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase: amlengine-db
        property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase: amlengine-db
        property: password
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    autoDeploy: true

  - type: web
    name: aml-portal
    env: java
    rootDir: aml-portal
    buildCommand: ./mvnw clean package || mvn clean package
    startCommand: java -jar target/*.jar
    plan: starter
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase: amlengine-db
        property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase: amlengine-db
        property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase: amlengine-db
        property: password
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    autoDeploy: true

  - type: web
    name: aml-engine
    env: java
    rootDir: aml-engine
    buildCommand: ./mvnw clean package || mvn clean package
    startCommand: java -jar target/*.jar
    plan: starter
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase: amlengine-db
        property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase: amlengine-db
        property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase: amlengine-db
        property: password
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    autoDeploy: true

  - type: web
    name: aml-frontend
    env: static
    rootDir: .
    buildCommand: yarn install && yarn build
    staticPublishPath: dist
    envVars:
      - key: VITE_ADMIN_API_URL
        value: https://aml-admin.onrender.com
      - key: VITE_PORTAL_API_URL
        value: https://aml-portal.onrender.com
    autoDeploy: true

databases:
  - name: amlengine-db
    plan: starter
    postgresMajorVersion: 15 