services:
  - type: web
    name: aml-admin
    env: java
    buildCommand: mvn clean install
    startCommand: java -jar aml-admin/target/aml-admin.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d201e92dbo4c73fv5nb0-a.frankfurt-postgres.render.com:5432/amlengine_db
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: 8FLqQ4m1VELiPdvK9amQI1hxwkBpvt3A

  - type: web
    name: aml-portal
    env: java
    buildCommand: mvn clean install
    startCommand: java -jar aml-portal/target/aml-portal.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d201e92dbo4c73fv5nb0-a.frankfurt-postgres.render.com:5432/amlengine_db
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: 8FLqQ4m1VELiPdvK9amQI1hxwkBpvt3A

  - type: web
    name: aml-engine
    env: java
    buildCommand: mvn clean install
    startCommand: java -jar aml-engine/target/aml-engine.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d201e92dbo4c73fv5nb0-a.frankfurt-postgres.render.com:5432/amlengine_db
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: 8FLqQ4m1VELiPdvK9amQI1hxwkBpvt3A 